# Generated by Django 5.1.3 on 2026-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("target_country", models.CharField(default="Germany", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LEAD", "New Lead"),
                            ("PREP", "IELTS/GRE Prep"),
                            ("APPLY", "University Applied"),
                            ("VISA", "Visa Processing"),
                        ],
                        default="LEAD",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
