# Generated by Django 5.1.3 on 2026-06-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_passport",
                    models.BooleanField(default=False, verbose_name="Valid Passport"),
                ),
                (
                    "has_transcripts",
                    models.BooleanField(
                        default=False, verbose_name="Attested Transcripts"
                    ),
                ),
                (
                    "has_sop",
                    models.BooleanField(
                        default=False, verbose_name="Statement of Purpose (SOP)"
                    ),
                ),
                (
                    "has_lor",
                    models.BooleanField(
                        default=False, verbose_name="Letters of Recommendation"
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.studentlead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ielts_band",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="IELTS Overall Band",
                    ),
                ),
                (
                    "gre_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="GRE Total Score"
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scores",
                        to="core.studentlead",
                    ),
                ),
            ],
        ),
    ]
